import type { MatchFirstSurveyQuestion } from '../../types/matchFirst';

export const matchFirstSurveyQuestions: MatchFirstSurveyQuestion[] = [
  {
    id: 'intent',
    type: 'single',
    titleKey: 'matchFirst.survey.questions.intent.title',
    required: true,
    options: [
      { value: 'buy', labelKey: 'matchFirst.survey.answers.intent.buy' },
      { value: 'rent', labelKey: 'matchFirst.survey.answers.intent.rent' },
      { value: 'both', labelKey: 'matchFirst.survey.answers.intent.both' },
    ],
  },
  {
    id: 'budget',
    type: 'budgetRange',
    titleKey: 'matchFirst.survey.questions.budget.title',
    helperKey: 'matchFirst.survey.questions.budget.helper',
    required: true,
  },
  {
    id: 'household_type',
    type: 'single',
    titleKey: 'matchFirst.survey.questions.household.title',
    required: true,
    options: [
      { value: 'single', labelKey: 'matchFirst.survey.answers.household.single' },
      { value: 'couple', labelKey: 'matchFirst.survey.answers.household.couple' },
      { value: 'family_young_child', labelKey: 'matchFirst.survey.answers.household.familyYoungChild' },
      { value: 'family_older_child', labelKey: 'matchFirst.survey.answers.household.familyOlderChild' },
      { value: 'starter', labelKey: 'matchFirst.survey.answers.household.starter' },
      { value: 'downsizing', labelKey: 'matchFirst.survey.answers.household.downsizing' },
    ],
  },
  {
    id: 'anchor_location',
    type: 'anchor',
    titleKey: 'matchFirst.survey.questions.anchor.title',
    helperKey: 'matchFirst.survey.questions.anchor.helper',
    required: true,
  },
  {
    id: 'commute',
    type: 'commuteSlider',
    titleKey: 'matchFirst.survey.questions.commute.title',
    helperKey: 'matchFirst.survey.questions.commute.helper',
    required: true,
  },
  {
    id: 'lifestyle_priorities',
    type: 'multi',
    titleKey: 'matchFirst.survey.questions.lifestyle.title',
    helperKey: 'matchFirst.survey.questions.lifestyle.helper',
    required: true,
    maxSelections: 3,
    options: [
      { value: 'green_access', labelKey: 'matchFirst.survey.answers.lifestyle.greenAccess' },
      { value: 'calmness', labelKey: 'matchFirst.survey.answers.lifestyle.calmness' },
      { value: 'public_transport', labelKey: 'matchFirst.survey.answers.lifestyle.publicTransport' },
      { value: 'schools_childcare', labelKey: 'matchFirst.survey.answers.lifestyle.schoolsChildcare' },
      { value: 'amenities', labelKey: 'matchFirst.survey.answers.lifestyle.amenities' },
      { value: 'affordability', labelKey: 'matchFirst.survey.answers.lifestyle.affordability' },
      { value: 'environmental_quality', labelKey: 'matchFirst.survey.answers.lifestyle.environmentalQuality' },
    ],
  },
  {
    id: 'must_haves',
    type: 'multi',
    titleKey: 'matchFirst.survey.questions.mustHaves.title',
    helperKey: 'matchFirst.survey.questions.mustHaves.helper',
    required: true,
    options: [
      { value: 'parks_nearby', labelKey: 'matchFirst.survey.answers.mustHaves.parksNearby' },
      { value: 'good_transit', labelKey: 'matchFirst.survey.answers.mustHaves.goodTransit' },
      { value: 'schools_nearby', labelKey: 'matchFirst.survey.answers.mustHaves.schoolsNearby' },
      { value: 'daily_shops', labelKey: 'matchFirst.survey.answers.mustHaves.dailyShops' },
      { value: 'low_traffic', labelKey: 'matchFirst.survey.answers.mustHaves.lowTraffic' },
      { value: 'bike_friendly', labelKey: 'matchFirst.survey.answers.mustHaves.bikeFriendly' },
      { value: 'garden_or_balcony', labelKey: 'matchFirst.survey.answers.mustHaves.gardenOrBalcony' },
    ],
  },
  {
    id: 'dealbreakers',
    type: 'multi',
    titleKey: 'matchFirst.survey.questions.dealbreakers.title',
    helperKey: 'matchFirst.survey.questions.dealbreakers.helper',
    required: false,
    options: [
      { value: 'high_noise', labelKey: 'matchFirst.survey.answers.dealbreakers.highNoise' },
      { value: 'busy_nightlife', labelKey: 'matchFirst.survey.answers.dealbreakers.busyNightlife' },
      { value: 'car_dependency', labelKey: 'matchFirst.survey.answers.dealbreakers.carDependency' },
      { value: 'poor_air_quality', labelKey: 'matchFirst.survey.answers.dealbreakers.poorAirQuality' },
      { value: 'flood_risk', labelKey: 'matchFirst.survey.answers.dealbreakers.floodRisk' },
      { value: 'low_listing_supply', labelKey: 'matchFirst.survey.answers.dealbreakers.lowListingSupply' },
    ],
  },
  {
    id: 'housing_types',
    type: 'multi',
    titleKey: 'matchFirst.survey.questions.housing.title',
    helperKey: 'matchFirst.survey.questions.housing.helper',
    required: true,
    options: [
      { value: 'apartment', labelKey: 'matchFirst.survey.answers.housing.apartment' },
      { value: 'row_house', labelKey: 'matchFirst.survey.answers.housing.rowHouse' },
      { value: 'family_house', labelKey: 'matchFirst.survey.answers.housing.familyHouse' },
      { value: 'new_build', labelKey: 'matchFirst.survey.answers.housing.newBuild' },
      { value: 'older_character', labelKey: 'matchFirst.survey.answers.housing.olderCharacter' },
      { value: 'garden', labelKey: 'matchFirst.survey.answers.housing.garden' },
    ],
  },
  {
    id: 'area_character',
    type: 'single',
    titleKey: 'matchFirst.survey.questions.area.title',
    required: true,
    options: [
      { value: 'lively_urban', labelKey: 'matchFirst.survey.answers.area.livelyUrban' },
      { value: 'quiet_city', labelKey: 'matchFirst.survey.answers.area.quietCity' },
      { value: 'suburban', labelKey: 'matchFirst.survey.answers.area.suburban' },
      { value: 'village', labelKey: 'matchFirst.survey.answers.area.village' },
      { value: 'rural_edge', labelKey: 'matchFirst.survey.answers.area.ruralEdge' },
    ],
  },
  {
    id: 'language',
    type: 'single',
    titleKey: 'matchFirst.survey.questions.language.title',
    required: true,
    options: [
      { value: 'en', labelKey: 'matchFirst.survey.answers.language.en' },
      { value: 'nl', labelKey: 'matchFirst.survey.answers.language.nl' },
    ],
  },
];

export const MATCH_FIRST_SURVEY_QUESTION_COUNT = matchFirstSurveyQuestions.length;
