"""PDF export service for Quick Brief and Full Dossier templates."""

import base64
import io
import logging
from datetime import date

from fpdf import FPDF

from app.models.risk import RiskCardsResponse, ViewingQuestionsResponse

logger = logging.getLogger(__name__)

_UNICODE_REPLACEMENTS = {
    "\u2014": "--",
    "\u2013": "-",
    "\u2018": "'",
    "\u2019": "'",
    "\u201c": '"',
    "\u201d": '"',
    "\u2026": "...",
    "\u00b7": " - ",
    "\u2022": "-",
}


def _sanitize(text: str) -> str:
    for char, replacement in _UNICODE_REPLACEMENTS.items():
        text = text.replace(char, replacement)
    return text.encode("latin-1", errors="replace").decode("latin-1")


def _severity_label(score: int | None) -> str:
    if score is None:
        return "N/A"
    if score >= 70:
        return "Good"
    if score >= 40:
        return "Moderate"
    if score >= 20:
        return "Poor"
    return "Critical"


def _severity_label_nl(score: int | None) -> str:
    if score is None:
        return "N.v.t."
    if score >= 70:
        return "Goed"
    if score >= 40:
        return "Matig"
    if score >= 20:
        return "Slecht"
    return "Kritiek"


def _risk_rows(
    risks: RiskCardsResponse | None,
    sunlight_score: int | None,
    is_nl: bool,
) -> list[tuple[str, str, str, str, str | None]]:
    rows: list[tuple[str, str, str, str, str | None]] = []
    severity_fn = _severity_label_nl if is_nl else _severity_label

    if risks:
        rows.append(
            (
                "Geluid" if is_nl else "Noise",
                str(risks.noise.score) if risks.noise.score is not None else "-",
                severity_fn(risks.noise.score),
                _sanitize((risks.noise.summary_nl if is_nl else risks.noise.summary) or ""),
                risks.noise.source_date,
            )
        )
        rows.append(
            (
                "Lucht" if is_nl else "Air Quality",
                str(risks.air_quality.score) if risks.air_quality.score is not None else "-",
                severity_fn(risks.air_quality.score),
                _sanitize(
                    (
                        risks.air_quality.summary_nl
                        if is_nl
                        else risks.air_quality.summary
                    )
                    or ""
                ),
                risks.air_quality.source_date,
            )
        )
        rows.append(
            (
                "Klimaat" if is_nl else "Climate",
                str(risks.climate_stress.score)
                if risks.climate_stress.score is not None
                else "-",
                severity_fn(risks.climate_stress.score),
                _sanitize(
                    (
                        risks.climate_stress.summary_nl
                        if is_nl
                        else risks.climate_stress.summary
                    )
                    or ""
                ),
                risks.climate_stress.source_date,
            )
        )

    rows.append(
        (
            "Zonlicht" if is_nl else "Sunlight",
            str(sunlight_score) if sunlight_score is not None else "-",
            severity_fn(sunlight_score),
            "",
            None,
        )
    )
    return rows


def _draw_header(pdf: FPDF, title: str, subtitle: str) -> None:
    pdf.set_font("Helvetica", "B", 18)
    pdf.cell(0, 10, title, new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(0, 6, subtitle, new_x="LMARGIN", new_y="NEXT")
    pdf.set_text_color(0, 0, 0)
    pdf.ln(4)


def _draw_footer(pdf: FPDF, is_nl: bool) -> None:
    pdf.ln(6)
    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(130, 130, 130)
    today = date.today().isoformat()
    generated = (
        f"Gegenereerd door buurt-check - {today}"
        if is_nl
        else f"Generated by buurt-check - {today}"
    )
    pdf.cell(0, 5, generated, new_x="LMARGIN", new_y="NEXT")
    disclaimer = (
        "Data is indicatief. Verifieer op locatie voor aankoop."
        if is_nl
        else "Data is indicative. Verify on-site before purchase."
    )
    pdf.cell(0, 5, disclaimer, new_x="LMARGIN", new_y="NEXT")
    sources = (
        "Bronnen: BAG, 3DBAG, RIVM, Klimaateffectatlas, CBS, EP-Online"
        if is_nl
        else "Sources: BAG, 3DBAG, RIVM, Klimaateffectatlas, CBS, EP-Online"
    )
    pdf.cell(0, 5, sources, new_x="LMARGIN", new_y="NEXT")


def _draw_viewing_questions(
    pdf: FPDF,
    viewing_questions: ViewingQuestionsResponse | None,
    is_nl: bool,
    max_questions: int | None,
) -> None:
    if not viewing_questions or not viewing_questions.categories:
        return
    pdf.set_font("Helvetica", "B", 12)
    header = "Vragen voor de bezichtiging" if is_nl else "Questions for your viewing"
    pdf.cell(0, 8, header, new_x="LMARGIN", new_y="NEXT")
    pdf.ln(1)

    count = 0
    for category in viewing_questions.categories:
        if max_questions is not None and count >= max_questions:
            break
        pdf.set_font("Helvetica", "B", 10)
        name = category.name_nl if is_nl else category.name
        pdf.cell(0, 7, _sanitize(name), new_x="LMARGIN", new_y="NEXT")
        pdf.set_font("Helvetica", "", 9)
        for question in category.questions:
            if max_questions is not None and count >= max_questions:
                break
            text = _sanitize(question.text_nl if is_nl else question.text_en)
            pdf.multi_cell(
                0,
                6,
                f"[ ] {text}",
                new_x="LMARGIN",
                new_y="NEXT",
            )
            count += 1
        pdf.ln(1)


def generate_quick_brief(
    address: str,
    building_year: int | None,
    building_use: str | None,
    risks: RiskCardsResponse | None,
    sunlight_score: int | None,
    viewing_questions: ViewingQuestionsResponse | None,
    shadow_image_b64: str | None = None,
    language: str = "en",
) -> bytes:
    """Generate a compact 1-page Quick Brief PDF."""
    is_nl = language == "nl"
    pdf = FPDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)

    _draw_header(
        pdf,
        "buurt-check",
        "BEZICHTIGINGSBRIEFING" if is_nl else "VIEWING BRIEFING",
    )

    pdf.set_font("Helvetica", "B", 14)
    pdf.cell(0, 8, _sanitize(address), new_x="LMARGIN", new_y="NEXT")
    facts: list[str] = []
    if building_year:
        facts.append(f"{'Bouwjaar' if is_nl else 'Built'} {building_year}")
    if building_use:
        facts.append(_sanitize(building_use))
    if facts:
        pdf.set_font("Helvetica", "", 10)
        pdf.set_text_color(100, 100, 100)
        pdf.cell(0, 6, " - ".join(facts), new_x="LMARGIN", new_y="NEXT")
        pdf.set_text_color(0, 0, 0)
    pdf.ln(4)

    if shadow_image_b64:
        try:
            image_data = base64.b64decode(shadow_image_b64)
            pdf.image(io.BytesIO(image_data), w=170, h=0)
            pdf.ln(4)
        except Exception:
            logger.warning("Failed to embed shadow snapshot in quick brief")

    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(
        0,
        8,
        "Risicobeoordeling" if is_nl else "Risk Assessment",
        new_x="LMARGIN",
        new_y="NEXT",
    )
    pdf.ln(1)

    col_w = [40, 20, 28, 102]
    pdf.set_font("Helvetica", "B", 9)
    pdf.set_fill_color(240, 241, 243)
    pdf.cell(col_w[0], 7, "Categorie" if is_nl else "Category", border=1, fill=True)
    pdf.cell(col_w[1], 7, "Score", border=1, fill=True, align="C")
    pdf.cell(col_w[2], 7, "Niveau" if is_nl else "Level", border=1, fill=True, align="C")
    pdf.cell(
        col_w[3],
        7,
        "Samenvatting" if is_nl else "Summary",
        border=1,
        fill=True,
        new_x="LMARGIN",
        new_y="NEXT",
    )
    pdf.set_font("Helvetica", "", 9)
    for category, score, level, summary, _ in _risk_rows(risks, sunlight_score, is_nl):
        pdf.cell(col_w[0], 7, category, border=1)
        pdf.cell(col_w[1], 7, score, border=1, align="C")
        pdf.cell(col_w[2], 7, level, border=1, align="C")
        pdf.cell(col_w[3], 7, summary[:58], border=1, new_x="LMARGIN", new_y="NEXT")
    pdf.ln(4)

    _draw_viewing_questions(pdf, viewing_questions, is_nl, max_questions=8)
    _draw_footer(pdf, is_nl)
    return bytes(pdf.output())


def generate_full_dossier(
    address: str,
    building_year: int | None,
    building_use: str | None,
    risks: RiskCardsResponse | None,
    sunlight_score: int | None,
    viewing_questions: ViewingQuestionsResponse | None,
    shadow_image_b64: str | None = None,
    language: str = "en",
) -> bytes:
    """Generate a 3-4 page Full Dossier PDF."""
    is_nl = language == "nl"
    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=15)

    # Page 1: cover + summary
    pdf.add_page()
    _draw_header(
        pdf,
        "buurt-check",
        "VOLLEDIG DOSSIER" if is_nl else "FULL DOSSIER",
    )
    pdf.set_font("Helvetica", "B", 14)
    pdf.multi_cell(0, 8, _sanitize(address), new_x="LMARGIN", new_y="NEXT")
    facts: list[str] = []
    if building_year:
        facts.append(f"{'Bouwjaar' if is_nl else 'Built'} {building_year}")
    if building_use:
        facts.append(_sanitize(building_use))
    if facts:
        pdf.set_font("Helvetica", "", 10)
        pdf.set_text_color(90, 90, 90)
        pdf.cell(0, 6, " - ".join(facts), new_x="LMARGIN", new_y="NEXT")
        pdf.set_text_color(0, 0, 0)
    pdf.ln(4)

    if shadow_image_b64:
        try:
            image_data = base64.b64decode(shadow_image_b64)
            pdf.image(io.BytesIO(image_data), w=170, h=0)
            pdf.ln(4)
        except Exception:
            logger.warning("Failed to embed shadow snapshot in full dossier")

    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(
        0,
        8,
        "Risico-overzicht" if is_nl else "Risk overview",
        new_x="LMARGIN",
        new_y="NEXT",
    )
    pdf.ln(1)
    col_w = [34, 18, 24, 76, 38]
    pdf.set_font("Helvetica", "B", 8)
    pdf.set_fill_color(240, 241, 243)
    pdf.cell(col_w[0], 7, "Categorie" if is_nl else "Category", border=1, fill=True)
    pdf.cell(col_w[1], 7, "Score", border=1, fill=True, align="C")
    pdf.cell(col_w[2], 7, "Niveau" if is_nl else "Level", border=1, fill=True, align="C")
    pdf.cell(col_w[3], 7, "Samenvatting" if is_nl else "Summary", border=1, fill=True)
    pdf.cell(col_w[4], 7, "Brondatum" if is_nl else "Source date", border=1, fill=True)
    pdf.ln()

    pdf.set_font("Helvetica", "", 8)
    for category, score, level, summary, source_date in _risk_rows(risks, sunlight_score, is_nl):
        pdf.cell(col_w[0], 7, category, border=1)
        pdf.cell(col_w[1], 7, score, border=1, align="C")
        pdf.cell(col_w[2], 7, level, border=1, align="C")
        pdf.cell(col_w[3], 7, summary[:46], border=1)
        pdf.cell(
            col_w[4],
            7,
            _sanitize(source_date or "-"),
            border=1,
            new_x="LMARGIN",
            new_y="NEXT",
        )

    # Page 2: risk details
    pdf.add_page()
    _draw_header(
        pdf,
        "buurt-check",
        "RISICODETAILS" if is_nl else "RISK DETAILS",
    )
    rows = _risk_rows(risks, sunlight_score, is_nl)
    for category, score, level, summary, source_date in rows:
        pdf.set_font("Helvetica", "B", 12)
        pdf.cell(0, 8, _sanitize(category), new_x="LMARGIN", new_y="NEXT")
        pdf.set_font("Helvetica", "", 10)
        score_line = (
            f"Score: {score}/100 - {level}"
            if score != "-"
            else f"Score: {score}"
        )
        pdf.multi_cell(0, 6, _sanitize(score_line), new_x="LMARGIN", new_y="NEXT")
        if summary:
            label = "Betekenis" if is_nl else "Meaning"
            pdf.multi_cell(
                0,
                6,
                _sanitize(f"{label}: {summary}"),
                new_x="LMARGIN",
                new_y="NEXT",
            )
        source_label = "Bron" if is_nl else "Source"
        source_text = source_date if source_date else ("Onbekend" if is_nl else "Unknown")
        pdf.multi_cell(
            0,
            6,
            _sanitize(f"{source_label} date: {source_text}"),
            new_x="LMARGIN",
            new_y="NEXT",
        )
        pdf.ln(2)

    # Page 3: viewing checklist
    pdf.add_page()
    _draw_header(
        pdf,
        "buurt-check",
        "BEZICHTIGINGSCHECKLIST" if is_nl else "VIEWING CHECKLIST",
    )
    _draw_viewing_questions(pdf, viewing_questions, is_nl, max_questions=None)
    if not viewing_questions or not viewing_questions.categories:
        pdf.set_font("Helvetica", "", 10)
        fallback = "Geen vragen beschikbaar." if is_nl else "No questions available."
        pdf.multi_cell(0, 6, fallback, new_x="LMARGIN", new_y="NEXT")

    # Page 4: methodology + notes
    pdf.add_page()
    _draw_header(
        pdf,
        "buurt-check",
        "METHODOLOGIE EN NOTITIES" if is_nl else "METHODOLOGY AND NOTES",
    )
    pdf.set_font("Helvetica", "", 10)
    methodology = (
        "Dit dossier combineert BAG, 3DBAG, RIVM, Klimaateffectatlas en CBS open data. "
        "Alle signalen zijn indicatief en geen juridisch of bouwkundig advies."
        if is_nl
        else "This dossier combines BAG, 3DBAG, RIVM, Klimaateffectatlas, and CBS open data. "
        "All signals are indicative and not legal or structural advice."
    )
    pdf.multi_cell(0, 6, _sanitize(methodology), new_x="LMARGIN", new_y="NEXT")
    pdf.ln(4)
    notes_title = "Notities bezichtiging" if is_nl else "Viewing notes"
    pdf.set_font("Helvetica", "B", 11)
    pdf.cell(0, 7, notes_title, new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 10)
    for _ in range(16):
        y = pdf.get_y() + 5
        pdf.line(pdf.l_margin, y, pdf.w - pdf.r_margin, y)
        pdf.ln(7)

    _draw_footer(pdf, is_nl)
    return bytes(pdf.output())
